CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
IMAGE_PLACEHOLDER = "<image-placeholder>"

FLOAT_TOKEN = "\u6570"  # 30354 数
FLOAT_TOKEN_ID = 30354
ROTATION_TOKEN = "\u8f6c"  # 31415 转
ROTATION_TOKEN_ID = 31415
APPEARANCE_TOKEN = "\u50cf"  # 31551 像
APPEARANCE_TOKEN_ID = 31551